- name: Install apache on web servers (Ubuntu)
  tags: apache,ubuntu
  ansible.builtin.apt:
    name:
      - apache2
      - libapache2-mod-php
  when: ansible_distribution == "Ubuntu"

- name: install apache on web servers (Fedora)
  tags: apache,fedora
  ansible.builtin.dnf:
    name: httpd
  when: ansible_distribution == "Fedora"

- name: ensure apache is running (ubuntu)
  tags: apache,ubuntu
  ansible.builtin.service:
    name: apache2
    state: started
  when: ansible_distribution == "Ubuntu"

- name: ensure apache is running (Fedora)
  tags: apache,fedora
  ansible.builtin.service:
    name: httpd
    state: started
  when: ansible_distribution == "Fedora"
